name: CI - FastProto
on:
  pull_request:
    branches:
      - main
      - 'releases/**'
  push:
    branches:
      - main
      - 'releases/**'

jobs:
  unit-tests:
    name:
    runs-on: ubuntu-latest
    container:
      image: maven:3.6.3-jdk-8
    timeout-minutes: 30

    steps:
      - name: checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 25
          ref: ${{ github.event.pull_request.head.sha }}

      - name: Cache local Maven repository
        uses: actions/cache@v2
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-
      - name: compile tests
        run: mvn test
